### ISSUE TITLE
IS this project finish.?

### ISSUE THREAD

**Issue by Nhatcao99** [SajithMR/Counting_plant_parts#1]
By the look of it, you have done a good work reconstruct the original repo to 3.6 This will save me a tone of time :D. 
But should you update the readme and the result?

**Comment by SajithMR** [comment]
Hi! This project did get kind of abandoned. Please let me know if you have any issues ill try to provide help. I'll add the results sometime this weekend.

**Comment by Nhatcao99** [comment]
Thank you for replying.
  I am looking forward to seeing the result, though.

**Comment by SajithMR** [comment]
Hi! Sorry I completely forgot about this, I have added a link to one of my posters on this project. hope that helps.
